# Enable body parse flag
enabled: ${body.enabled:true}
# cache request body as a String along with JSON object
cacheRequestBody: ${body.cacheRequestBody:false}
# A list of applied request path prefixes, other requests will skip this handler. The value can be a string
# if there is only one request path prefix needs this handler. or a list of strings if there are multiple.
appliedPathPrefixes: ${body.appliedPathPrefixes:}
