# Email Sender Configuration
# Email server host name or IP address
host: ${email.host:mail.lightapi.net}
# Email SMTP port number. Please don't use port 25 as it is not safe
port: ${email.port:587}
# Email user or sender address.
user: ${email.user:noreply@lightapi.net}
# Email password. If you want to put the email.pass in values.yml, you must encrypt it.
# If you don't want to put the password in the config file, you can use the following environment variable.
# EMAIL_PASS=password
pass: ${email.pass:password}
# Email debug mode. Default to true
debug: ${email.debug:true}
# Email authentication. Default to true
auth: ${email.auth:true}
