
# enable/disable the handler.
enabled: ${expect-100-continue.enabled:true}

# List of paths that will not follow the expect-100-continue protocol. The Expect header will be removed altogether.
# format is in array format, or in string array format (i.e. '[path1, path2]')
ignoredPaths: ${expect-100-continue.ignored-paths:}