#indicator of enabled
enabled: ${response-injection.enabled:true}
#response body injection applied path prefixes. Injecting the response body and output into the audit log is very heavy operation,
#and it should only be enabled when necessary or for diagnose session to resolve issues. This list can be updated on the config
#server or local values.yml, then an API call to the config-reload endpoint to apply the changes from light-portal control pane.
#Please be aware that big response body will only log the beginning part of it in the audit log and gzip encoded response body can
#not be injected. Even the body injection is not applied, you can still transform the response for headers, query parameters, path
#parameters etc. The format is a list of strings separated with commas or a JSON list in values.yml definition from config server,
#or you can use yaml format in this file or values.yaml on local filesystem. The following are the examples.
#response-injection.appliedBodyInjectionPathPrefixes: ["/v1/cats", "/v1/dogs"]
#response-injection.appliedBodyInjectionPathPrefixes: /v1/cats, /v1/dogs
#response-injection.appliedBodyInjectionPathPrefixes:
#  - /v1/cats
#  - /v1/dogs
appliedBodyInjectionPathPrefixes: ${response-injection.appliedBodyInjectionPathPrefixes:}
