# response-filter.yml

# indicate if the interceptor is enabled or not.
enabled: ${response-filter.enabled:true}
# A list of applied request path prefixes, other requests will skip this handler. The value can be a string
# if there is only one request path prefix needs this handler. or a list of strings if there are multiple.
appliedPathPrefixes: ${response-filter.appliedPathPrefixes:}
