baseurl = "https://networknt.github.io/light-java/"
languageCode = "en-us"
title = "Light Java - The fastest Java API Framework"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Steve Hu"
	description = "Light Java Docs"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/networknt/light-java"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "stevehu"
	email   = "stevehu@gmail.com"


[[menu.main]]
	name   = "Introduction"
	url    = "/index.html"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10


[[menu.main]]
	name   = "Architecture"
	url    = "architecture/"
	weight = 20

[[menu.main]]
	name   = "Middleware"
	url    = "middleware/"
	weight = 30

[[menu.main]]
	name   = "Other Components"
	url    = "other/"
	weight = 30

[[menu.main]]
	name   = "Tutorials"
	url    = "tutorials/"
	weight = 40

[[menu.main]]
	name   = "Examples"
	url    = "example/"
	weight = 45

[[menu.main]]
	name   = "Tools"
	url    = "tools/"
	weight = 50

[[menu.main]]
	name   = "Issues & Help"
	url    = "https://github.com/networknt/light-java/issues"
	weight = 60

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 70

[[menu.main]]
	name   = "License"
	url    = "https://www.apache.org/licenses/LICENSE-2.0"
	weight = 80


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
